### ISSUE TITLE
Email copy

### ISSUE THREAD

**Issue by vksantosh** [micahherstand/shalomshanti#12]
SUBJECT 
Save the date: July 10, 2016 – Wedding of Vidya Santosh and Micah Herstand

BODY
Dear friends and family,

Mark your calendars; we have set a date for our wedding! It would be a pleasure to have you there to affirm and celebrate our marriage. Please click one of the red response circles below to visit our website and provide some helpful information for planning. 

[image]

If the above image is not loading, please click here to access the website.

**Comment by vksantosh** [comment]
Also image could be a _bit_ smaller. :)

**Comment by herstand** [comment]
Image is 600w x 749h

![image](https://cloud.githubusercontent.com/assets/950515/11793275/99b7c622-a278-11e5-883e-dda63a871c8b.png)

**Comment by herstand** [comment]
I'm not sure "to access the website" makes sense. If they haven't seen the image, it's not clear why they have to go to the website. We should have a call to action in the text as well.

**Comment by vksantosh** [comment]
Yeah, I used to have a reference to the website, but we cut it out. How about "...to provide us some information for planning purposes." ?

**Comment by herstand** [comment]
How's this?

![image](https://cloud.githubusercontent.com/assets/950515/11795586/8ca54b82-a285-11e5-9338-d6dcc5cdd7aa.png)
